disinfecto/disinfecto/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (password_reset, password_reset_done, 
password_reset_confirm, password_reset_complete
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls', namespace = 'product')),
    path('password_reset', password_reset, name='password_reset'),
    path('password_reset_done', password_reset_done, name='password_reset_done'),
    path('reset/<uidb64>/<token>', password_reset_confirm, name='password_reset_confirm'),
    path('reset/done', password_reset_complete, name='password_reset_complete')
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

disinfecto/product/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import (login, logout, password_reset, password_reset_done,
password_reset_confirm, password_reset_complete
)

app_name = 'product'

urlpatterns = [
    path('', index, name = 'index'),
    path('complaint', complaint, name = 'complaint'),
    path('inquiry', inquiry, name = 'inquiry'),
    path('allproducts', getAllProducts, name='allproducts'),
    path('reviews', giveReview, name='giveReview'),
    path('login', login, name = 'login'),
    path('signup', signup, name = 'signup'),
    path('logout', logout, {'next_page': '/'}, name = 'logout'),
    path('home', home, name = 'home'),
    path('services', getServices, name = 'services'),
    path('payment', payment, name='payment'),
    # path('product/<product_id>/', productorder, name='productorder'),
    path('feedback', feedback, name='feedback'),
    path('success/', success, name='success'),
    path('cart', addtocart, name='addtocart'),
    path('showcart', showcart, name='showcart'),
    path('refund_policy', refund_policy, name='refund_policy'),
    path('terms_of_condition', terms_of_condition, name='terms_of_condition'),
    path('privacy_policy', privacy_policy, name='privacy_policy'),
]

disinfecto/product/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model
from . import constants as user_constants
from .managers import *


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, null=True, db_index=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)
    phone = models.CharField(max_length=10, null=True, blank=True)

    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'

    objects = UserManager()



class Profile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name="user_profile")
    phone = models.CharField(max_length=10, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.email



class Product(models.Model):
    name = models.CharField(max_length=60)
    image = models.ImageField()
    size = models.CharField(max_length=5, null=True, blank=True)
    colour = models.CharField(max_length=20, null=True, blank=True)
    price = models.FloatField()
    qty = models.IntegerField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)


    def __str__(self):
        return self.name


class Service(models.Model):
    name = models.CharField(max_length=60)
    image = models.ImageField()
    price = models.FloatField()
    
    def __str__(self):
        return self.name


class Order(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    phone = models.CharField(max_length=10, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True)
    service = models.ForeignKey(Service, on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.IntegerField(default=1)
    total = models.CharField(max_length=20, null=True, blank=True)
    razorpay_order_id = models.CharField(max_length=60, null=True, blank=True)
    order_success = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True)



    def __str__(self):
        return self.user.email



class Feedback(models.Model):
    email = models.EmailField(max_length=100)
    description = models.TextField()


    def __str__(self):
        return self.email


class BannerImage(models.Model):
    image = models.ImageField()
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.image.url

class Review(models.Model):
    customer_name = models.CharField(max_length=30, null=True, blank=True)
    review_text = models.TextField(null=True, blank=True)
    ratings = models.PositiveIntegerField()
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.customer_name


class Cart(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    service = models.ForeignKey(Service, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    price = models.FloatField()

    def __str__(self):
        return self.user.first_name

disinfecto/product/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django import forms


class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=60, widget=forms.TextInput(attrs={'class': "input"}))
    last_name = forms.CharField(max_length=60, widget=forms.TextInput(attrs={'class': "input"}))
    phone = forms.CharField(max_length=60, widget=forms.TextInput(attrs={'class': "input", "type": 'tel'}))
    email = forms.CharField(max_length=60, widget=forms.TextInput(attrs={'class': "input", 'type': 'email'}))
    password1 = forms.CharField(max_length=60, widget=forms.TextInput(attrs={'class': "input", 'type': 'password'}))
    password2 = forms.CharField(max_length=60, widget=forms.TextInput(attrs={'class': "input", 'type': 'password'}))

    class Meta(UserCreationForm):
        model = User
        fields = ('first_name', 'last_name', 'phone', 'email', 'password1', 'password2')

disinfecto/product/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.conf import settings
from .forms import *
from .models import *
from django.contrib.auth import login, authenticate
from django.core.mail import send_mail
from ast import literal_eval
from django.db.models import Sum
from .helpers import saveOrder, sendOrderEmail
import requests
import hmac
import hashlib


def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(email=email, password=raw_password)
            login(request, user)
            return redirect('product:home')
    else:
        form = CustomUserCreationForm()
    return render(request, 'signup.html', {
        'form': form
    })


@login_required
def home(request):
    if request.method == 'GET':
        products = Product.objects.all()
        return render(request, 'products.html', {
            'products':products
        })


@login_required
def getServices(request):
    if request.method == 'GET':
        services = Service.objects.all()
        return render(request, 'services.html', {
            'services': services
        })


@login_required
def payment(request):
    if request.method == 'POST':
        data = request.body.decode('utf-8')
        # razorpay data payload
        data = literal_eval(data)
        # razorpay_payment_url
        razorpay_payment_url = 'https://api.razorpay.com/v1/orders'
        # razorpay headers
        headers = {
            'Content-Type': 'application/json',
            'Authorization': 'Basic cnpwX3Rlc3RfR0VqOW16NVY4NnFNNmY6MUxvazBsZXZHc2VYeGQ4N2czY0ZSWVNp'
        }
        response = requests.post(razorpay_payment_url,
            json=data,
            headers=headers
        ).json()

        return JsonResponse({
            'amount': response.get('amount'),
            'order_id': response.get('id')           
        })
    else:
        return render(request, 'razorpay_form.html', {
            'amount': request.GET.get('amount'),
            'order_id': request.GET.get('id')
        })


# @login_required
# def productorder(request, product_id):
#     if request.method == 'GET':
#         products = Product.objects.get(id=int(product_id))
#         return render(request, 'order.html', {'products':products})
#     else:
#         products = Product.objects.get(id=product_id)
#         quantity = request.POST.get('quantity')
#         if int(quantity) <= int(products.qty):

#             total = int(products.price) * int(quantity)
#             response = requests.post('https://api.razorpay.com/v1/orders',
#             json={
#             'amount': total*100,
#             'currency': 'INR',
#             'payment_capture':1
#             },
#             headers={'content-type':'application/json',
#             'Authorization': 'Basic cnpwX3Rlc3RfWk13MklkM3JsZExrbTA6UjdQaFRYaVdqb0o1WW9lc0FJNGRpUlJR'
#             }).json()
#             amount = response.get('amount')
#             order_id = response.get('id')
#             return render(request, 'razorpay_form.html', {
#                 'amount': amount,
#                 'order_id': order_id,
#                 'name': products.name,
#                 'product_id': products.id,
#                 'total': total,
#                 'quantity': quantity
#             })
#         else:
#             return render(request, 'order.html', {'error':"Quantity is Not Available"})


@login_required
def feedback(request):
    if request.method == 'GET':
        return render(request, 'feedback.html')
    else:
        email = request.POST.get('email')
        message = request.POST.get('msg')
        send_mail('Dr Disinfecto Customer FeedBack', message, email, [settings.EMAIL_HOST_USER])
        return redirect('home')


@login_required
def success(request):
    if request.method == 'POST':
        if 'error' in request.POST:
            return HttpResponse('payment not completed')
        else:
            # got the response postback data
            razorpay_order_id = request.POST.get('razorpay_order_id')
            razorpay_payment_id = request.POST.get('razorpay_payment_id')
            razorpay_signature = request.POST.get('razorpay_signature')
            # payment string
            payment_string = razorpay_order_id + '|' + razorpay_payment_id
            # generate the hashed string
            signature = hmac.new(bytes('1Lok0levGseXxd87g3cFRYSi', 'latin-1'),
            msg=bytes(payment_string, 'latin-1'),
            digestmod=hashlib.sha256
            ).hexdigest().upper()
            # verify the payment integrity
            if signature == razorpay_signature:
                items = Cart.objects.filter(user=request.user.pk)
                for item in items:
                    if not item.service:
                        product = Product.objects.get(id=item.product.pk)
                        product.qty = int(product.qty) - int(item.quantity)
                        product.save()
                        payload = {
                            'user': request.user,
                            'phone': request.POST.get('mobile'),
                            'address': request.POST.get('address'),
                            'product': product,
                            'quantity': item.quantity,
                            'total': item.price,
                            'razorpay_order_id': razorpay_order_id,
                            'order_success': True
                        }
                        saveOrder(**payload)
                    else:
                        service = Service.objects.get(id=item.service.pk)
                        payload = {
                            'user': request.user,
                            'phone': request.POST.get('mobile'),
                            'address': request.POST.get('address'),
                            'service': service,
                            'quantity': 0,
                            'total': item.price,
                            'razorpay_order_id': razorpay_order_id,
                            'order_success': True
                        }
                        saveOrder(**payload)
                items.delete()
                order_msg = f'''
                    Dear Dr Disinfecto Team,\n
                    Customer- {request.user.first_name}\n
                    Phone number- {request.user.phone}\n

                    Has Successfully placed an order
                '''
                sendOrderEmail(order_msg, request.user.email)
                return HttpResponse('Payment done Order placed successfully')
            else:
                return HttpResponse('payment failed')


def index(request):
    if request.method == 'GET':
        images = BannerImage.objects.all()
        reviews = Review.objects.all()
        return render(request, 'home.html', {
            'images': images,
            'reviews': reviews
        })


def getAllProducts(request):
    if request.method == 'GET':
        products = Product.objects.all()
        return render(request, 'index.html', {
            'products': products
        })


@login_required
def giveReview(request):
    if request.method == 'GET':
        return render(request, 'review.html', {
            'username': request.user.first_name
        })
    else:
        Review.objects.create(
            user=request.user,
            product_name=request.POST.get('product_name'),
            review_text=request.POST.get('review'),
            ratings=request.POST.get('rating')
        )
        return redirect('product:home')


def inquiry(request):
    if request.method == 'POST':
        message = f'''
            This is the formal inquiry by the customer {request.POST.get('customer_name')} \n
            Customer additonal details:- \n
            Email- {request.POST.get('email')}\n
            Phone Number- {request.POST.get('phone')}\n
            Inquiry is below :-\n
            {request.POST.get('inquiry_text')}
        '''
        send_mail('Dr Disinfecto Customer Inquiry', message, request.POST.get('email'), [settings.EMAIL_HOST_USER])
        return redirect('product:index')


def complaint(request):
    if request.method == 'POST':
        message = f'''
            This is the complaint by the customer {request.POST.get('customer_name')} \n
            Customer additonal details:- \n
            Email- {request.POST.get('email')}\n
            Phone Number- {request.POST.get('phone')}\n
            Complaint is below :-\n
            {request.POST.get('complaint_text')} 
        '''
        send_mail('Dr Disinfecto Customer Complaint', message, request.POST.get('email'), [settings.EMAIL_HOST_USER])
        return redirect('product:index')


@login_required
def addtocart(request):
    if request.method == 'POST':
        data = request.body.decode('utf-8')
        data = literal_eval(data)
        if data.get('product'):
            product = Product.objects.get(id=data.get('id'))
            total_price = product.price * data.get('quantity')
            Cart.objects.create(
                user=request.user,
                product=product,
                quantity=data.get('quantity'),
                price=total_price
            )
            return HttpResponse("product added into cart")
        else:
            service = Service.objects.get(id=data.get('id'))
            Cart.objects.create(
                user=request.user,
                service=service,
                quantity=0,
                price=service.price
            )
            return HttpResponse("service added into cart")

disinfecto/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>DR. DISINFECTO</title>
    <link rel="stylesheet" href="{% static 'css/bulma.min.css' %}">
    <link rel="stylesheet" href="https://kit-free.fontawesome.com/releases/latest/css/free.min.css" media="all">
    <link rel="stylesheet" href="https://kit-free.fontawesome.com/releases/latest/css/free-v4-font-face.min.css" media="all">
    <link rel="stylesheet" href="https://kit-free.fontawesome.com/releases/latest/css/free-v4-shims.min.css" media="all">
  </head>
<body class="has-background-white-hter">
  {% block body %} {% endblock %}
</body>
</html>

disinfecto/templates/cartitems.html
{% extends 'base.html' %}
{% load extras %}

{% block body %}

{% include 'navbar.html' %}

<br>

<section class="hero is-info">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">Dr Disinfecto Shopping Cart</h1>
      <h2 class="subtitle">
        Dear {{ request.user.first_name }}
      </h2>
    </div>
  </div>
</section>

{% if total_price is None %}
<section class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-6">
                <article class="message is-info">
                    <div class="message-header">
                      <p>Cart is empty</p>
                      <button class="delete" aria-label="delete"></button>
                    </div>
                    <div class="message-body">
                        No items in the cart yet.
                    </div>
                  </article>                
            </div>
        </div>
    </div>
</section>
{% else %}
<section class="section">
    <div class="container">
      <div class="columns is-centered">
        <div class="column is-6">
          <div class="container">
              <nav class="panel">
                  <p class="panel-heading">
                    Total Price- <strong>{{ total_price }}</strong>
                  </p>
                  <div class="columns is-multiline">
                      {% for item in items %}
                      <div class="column is-full">
                          <div class="level box">
                            {% if item.product.id %}
                              <div class="level-left">
                                  <p style="text-transform: capitalize;">{{ item.product.id|getname }} (Qty- {{ item.quantity }})</p>
                              </div>
                            {% else %}
                              <div class="level-left">
                                  <p style="text-transform: capitalize;">{{ item.service.id|getsname }}</p>
                              </div>
                            {% endif %}
                              <div class="level-right">
                                  <p>{{ item.price }}</p>&nbsp;
                                  <button class="button" onclick="removeItem('{{ item.pk }}');">
                                      <span class="icon">
                                          <i class="fas fa-trash"></i>
                                      </span>                                
                                  </button>
                              </div>
                          </div>
                      </div>
                      {% endfor %}
                  </div>
                  <div class="panel-block">
                    <button class="button is-link is-outlined is-fullwidth"
                    onclick="checkout();">
                      Checkout
                    </button>
                  </div>
              </nav>    
          </div>
        </div>
      </div>
    </div>
  </section>
{% endif %}

{% include 'csrfcookie.html' %}

<script>
    const removeItem = (id) => {
        const carturl = `{% url 'product:addtocart' %}?id=${parseInt(id)}`;
        fetch(carturl, {
            method: 'DELETE',
            headers: {
                "X-CSRFToken": csrftoken
            }
        })
        .then(success=> window.location.reload())
        .catch(err=> alert('Error occurred'));
    };

    const checkout = () => {
      const paymenturl = "{% url 'product:payment' %}";

      headers = {
        'Content-Type': 'application/json',
        'X-CSRFToken': csrftoken
      }

      payload = {
        'amount': parseFloat('{{ total_price }}')*100,
        'currency': 'INR',
        'payment_capture': 1
      }

      fetch(paymenturl, {
        method: 'POST',
        headers: headers,
        body: JSON.stringify(payload)
      })
      .then(success=> {
        success.json()
        .then(resp=> window.location.href=`${paymenturl}?amount=${resp.amount}&id=${resp.order_id}`)
        .catch(err=>alert('error occured'));
      })
      .catch(err=> console.log(err));
    };
</script>


{% endblock %}

disinfecto/templates/footer.html
<footer class="footer">
    <div class="container">
      <div class="content has-text-centered">
        <div class="soc">
          <a href="https://fb.com/dr.disinfecto" target="_blank"><i class="fa fa-facebook fa-lg fa-2x" aria-hidden="true"></i></a> &nbsp;
          <a href="https://www.instagram.com/dr.disinfecto/" target="_blank"><i class="fa fa-instagram fa-lg fa-2x" aria-hidden="true"></i></a>&nbsp;
          <a href="https://twitter.com/DrDisinfecto" target="_blank"><i class="fa fa-twitter fa-lg fa-2x" aria-hidden="true"></i></a>
        </div>
        <br>
        <p class="title is-5">
          We are based in <i>New Delhi</i> 
        </p>
        <p class="title is-5">
          For more details please contact us at <br><br><b><a href="#">+91 9818427577</a></b> 
        </p>
      </div>
      <div class="content has-text-centered">
        <p><a href="{% url 'product:privacy_policy' %}">Privacy Policy</a> | <a href="{% url 'product:refund_policy' %}">Refund Policy</a> | <a href="{% url 'product:terms_of_condition' %}">Terms of condition</a></p>
      </div>
    </div>
  </footer>

disinfecto/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% load extras %}

{% block body %}

<style>
  .hero.is-black {
    background-color: #0d335a;
  }
/* Slideshow container */
.slideshow-container {
  max-width: 65%;
  position: relative;
  margin: auto;
}

/* Hide the images by default */
.mySlides {
  display: none;
}

/* Next & previous buttons */
.prev, .next {
  cursor: pointer;
  position: absolute;
  top: 50%;
  width: auto;
  margin-top: -22px;
  padding: 16px;
  color: white;
  font-weight: bold;
  font-size: 18px;
  transition: 0.6s ease;
  border-radius: 0 3px 3px 0;
  user-select: none;
}

/* Position the "next button" to the right */
.next {
  right: 0;
  border-radius: 3px 0 0 3px;
}

/* On hover, add a black background color with a little bit see-through */
.prev:hover, .next:hover {
  background-color: rgba(0,0,0,0.8);
}

/* Caption text */
.text {
  color: #f2f2f2;
  font-size: 15px;
  padding: 8px 12px;
  position: absolute;
  bottom: 8px;
  width: 100%;
  text-align: center;
}

/* Number text (1/3 etc) */
.numbertext {
  color: #f2f2f2;
  font-size: 12px;
  padding: 8px 12px;
  position: absolute;
  top: 0;
}

/* The dots/bullets/indicators */
.dot {
  cursor: pointer;
  height: 15px;
  width: 15px;
  margin: 0 2px;
  background-color: #bbb;
  border-radius: 50%;
  display: inline-block;
  transition: background-color 0.6s ease;
}

.active, .dot:hover {
  background-color: #717171;
}

/* Fading animation */
.fade {
  -webkit-animation-name: fade;
  -webkit-animation-duration: 1.5s;
  animation-name: fade;
  animation-duration: 1.5s;
}

@-webkit-keyframes fade {
  from {opacity: .4}
  to {opacity: 1}
}

@keyframes fade {
  from {opacity: .4}
  to {opacity: 1}
}

@media screen and (min-width: 350px) and (max-width: 546px) {
    .slideshow-container {
      max-width: 100%;
      position: relative;
      margin: auto;
    }
    .container.is-fluid {
      padding: 0;
    }
  }

</style>

{% include 'navbar.html' %}

<br>

<!-- Inquiry form -->
<section class="hero is-black" id='inquiry'>
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Inquiry
      </h1>
      <h2 class="subtitle">
        Drop us any Inquiry, we will reach out to you shortly.
      </h2>  
    </div>
  </div>
</section>

<section class="section">
  <div class="container is-fluid">
    <form method="post" action="{% url 'product:inquiry' %}">
      {% csrf_token %}
    <div class="field">
      <p class="control has-icons-left has-icons-right">
        <input class="input" type="text" name="customer_name" placeholder="Name">
        <span class="icon is-small is-left">
          <i class="fas fa-user"></i>
        </span>
      </p>
    </div>
    <div class="field">
      <p class="control has-icons-left has-icons-right">
        <input class="input" type="email" name="email" placeholder="Email">
        <span class="icon is-small is-left">
          <i class="fas fa-envelope"></i>
        </span>
        <span class="icon is-small is-right">
          <i class="fas fa-check"></i>
        </span>
      </p>
    </div>
    <div class="field">
      <p class="control has-icons-left">
        <input class="input" type="tel" name="phone" placeholder="Phone">
        <span class="icon is-small is-left">
          <i class="fas fa-phone"></i>
        </span>
      </p>
    </div>
    <div class="field">
      <div class="control">
        <textarea class="textarea" name="inquiry_text" placeholder="Explain how we can help you"></textarea>
      </div>
    </div>
    <div class="field">
      <p class="control">
        <button type="submit" class="button is-success is-medium is-rounded">
          Send Inquiry
        </button>
      </p>
    </div>
  </form> 
  </div>
</section>

<br>

<section class="section">
  <div class="container is-fluid">
    <!-- Slideshow container -->
    <div class="slideshow-container">

      {% for image in images %}
      <div class="mySlides fade">
        <div class="numbertext">{{forloop.counter}}</div>
        <img src="{{image.image.url}}" style="width:100%; height:450px;">
      </div>
      {% endfor %}
      <!-- Next and previous buttons -->
      <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
      <a class="next" onclick="plusSlides(1)">&#10095;</a>
    </div>
    <br>

    <!-- The dots/circles -->
    <div style="text-align:center">
      {% for image in images %}
        <span class="dot" onclick="currentSlide('{{forloop.counter}}')"></span>
      {% endfor %}
    </div>
  </div>
</section>

<br>

<!-- Reviews -->
<section class="hero is-black" id='reviews'>
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Reviews
      </h1>
      <h2 class="subtitle">
        What customers think about our products.
      </h2>  
    </div>
  </div>
</section>

<section class="section">
  <div class="columns">
    {% for review in reviews %}
    <div class="column is-one-fifth card">
      <div class="card-header">
        <p class="subtitle">{{ review.customer_name }}</p>
      </div>
      <div class="card-content">
        <p>{{ review.review_text }}</p>
      </div>
      <footer class="card-footer  has-text-centered">
        {% for rating in review.ratings|times %}
          <span class="icon">
            <i class="fas fa-star"></i>
          </span>
        {% endfor %}
      </footer>
    </div>
    {% endfor %}
  </div>    
</section>

<br>

<!-- About us -->
<section class="hero is-black" id='aboutus'>
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        About Us
      </h1>
    </div>
  </div>
</section>

<br>

<section class="section">
  <div class="container">
    <div class="columns has-text-centered">
      <div class="column is-4 card">
        <div class="card-header">
          <p class="title">SANITIZING SERVICES</p>
        </div>
        <div class="card-content">
          <p class="subtitle">Residental</p>
          <p class="subtitle">Work Places</p>
          <p class="subtitle">Private Vehicles</p>
          <p class="subtitle">Commercial Vehicles</p>  
        </div>
    </div>
      <div class="column is-4 card">
        <div class="card-header">
          <p class="title">HEALTH CARE PRODUCTS</p>
        </div>
        <div class="card-content">
          <p class="subtitle">Sanitizers</p>
          <p class="subtitle">Face Masks</p>
          <p class="subtitle">PPE Kits</p>
          <p class="subtitle">Disinfectant Chemicals</p>
          <p class="subtitle">Infrared Thermometers</p>
        </div>
      </div>
      <div class="column is-4 card">
        <div class="card-header">
          <p class="title">KEY BENEFITS</p>
        </div>
        <div class="card-content">
          <p class="subtitle">Dedicated Services</p>
          <p class="subtitle">Best Quality Products</p>
          <p class="subtitle">Never Ending Discounts</p>
          <p class="subtitle">Promo Offers</p>
        </div>
      </div>
    </div>
  </div>
</section>

<br>

<!-- Contact us -->
<section class="hero is-black" id='contactus'>
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Contact Us
      </h1>
      <h2 class="subtitle">
        Share Your Valuable Feedback.
      </h2>  
    </div>
  </div>
</section>

<section class="section">
  <div class="container is-fluid">
    <div class="columns">
      <div class="column is-12">
        {% include 'footer.html' %}
      </div>
    </div>
  </div>
</section>

<script>
  var slideIndex = 1;
showSlides(slideIndex);

// Next/previous controls
function plusSlides(n) {
  showSlides(slideIndex += n);
}

// Thumbnail image controls
function currentSlide(n) {
  console.log(n);
  n = parseInt(n);
  showSlides(slideIndex = n);
}

function showSlides(n) {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("dot");
  if (n > slides.length) {slideIndex = 1}
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";
  }
  for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " active";
}
</script>

{% endblock %}